$PROBLEM Simulation of population data w/ covariates
$INPUT ID TIME WT AMT DV
$DATA   SIMORIG IGNORE=#
$SUBROUTINE ADVAN1
$PK
IF (ICALL.EQ.4) THEN
WT=70+70*ETA(3)
ENDIF
CL=THETA(1)*WT*EXP(ETA(1))
IF (ICALL.EQ.4) THEN
V=THETA(2)*EXP(ETA(2)) ; Simulated V
ELSE
V=THETA(3)+ETA(4) ; Non-simulated V
ENDIF
K=CL/V
S1=V
$ERROR
IF (ICALL.EQ.4) THEN
Y=F+F*EPS(1)
ELSE
Y=F+F*EPS(2)
ENDIF
$THETA (0, 0.0625, )
10 FIX
(0, 12, )
$OMEGA 0.09   
0.05 FIX  
0.04 FIX  
4.00  
$SIGMA 0.01 FIX  
0.03  
$SIMULATION (9215690)  SUBPROBLEMS= 10  
$ESTIMATION 
$TABLE ID TIME WT AMT APPEND NOHEADER NOPRINT FILE=SIMDATA3
