$PROB NM7 test 1
$INPUT SID SEX AGE RACE HT SMOK HCTZ PROP CON AMT WT TIME SECR DV DROP=RATE EVID SS II ID OCC
$DATA   Data1 IGNORE=@
$SUBROUTINE ADVAN2 TRANS2
$PK 
TVCL=THETA(1)
TVV=THETA(2)
TVKA=THETA(3)
CL=TVCL*EXP(ETA(1))
V =TVV *EXP(ETA(2))
KA=TVKA*EXP(ETA(3))
S2=V
$THETA 18.7
87.3
2.13
$OMEGA 0.128   
0.142  
$OMEGA 1.82  
$ERROR 
IPRED = F
IRES  = DV - F
W     = F
IF(W.EQ.0) W = 1
IWRES = IRES/W
Y     = IPRED + W*EPS(1)
$SIGMA 0.0231  
$EST METHOD=ITS INTERACTION FILE=TestData1.EXT CTYPE=3 NITER=1000 PRINT=5 NOABORT MSFO=testdata1.MSF NSIG=3 SIGL=6
 $EST METHOD=SAEM NBURN=2000 NITER=500 PRINT=100
$COV MATRIX=R 

$TABLE ID TIME IPRED IWRES WT ETA1 APPEND ONEHEADER NOPRINT FILE=XXXX
